import * as React from "react";
import { Tree, TreeItem, TreeItemLayout } from "@fluentui/react-components";

// Generated by https://quicktype.io

export interface Type {
  id: number;
  name: string;
  children?: Type[];
}

const treeData: Type[] = [
  {
    id: 1,
    name: "A",
    children: [
      {
        id: 2,
        name: "A.1",
        children: [
          {
            id: 3,
            name: "A.1.1",
          },
        ],
      },
    ],
  },
];

export const Default = () => {
  const renderTree = (nodes: Type[]) => {
    return (
      <Tree aria-label="Default">
        {nodes.map((node) => {
          return (
            <TreeItem itemType={node.children ? "branch" : "leaf"} key={node.id} value={node.name}>
              <TreeItemLayout>{node.name}</TreeItemLayout>
              {node.children && renderTree(node.children)}
            </TreeItem>
          );
        })}
      </Tree>
    );
  };

  return (
    <div>
      <Tree aria-label="Default">
        <TreeItem itemType="branch">
          <TreeItemLayout>level 1, item 1</TreeItemLayout>
          <Tree>
            <TreeItem itemType="leaf">
              <TreeItemLayout>level 2, item 1</TreeItemLayout>
            </TreeItem>
            <TreeItem itemType="leaf">
              <TreeItemLayout>level 2, item 2</TreeItemLayout>
            </TreeItem>
            <TreeItem itemType="leaf">
              <TreeItemLayout>level 2, item 3</TreeItemLayout>
            </TreeItem>
          </Tree>
        </TreeItem>
        <TreeItem itemType="branch">
          <TreeItemLayout>level 1, item 2</TreeItemLayout>
          <Tree>
            <TreeItem itemType="branch">
              <TreeItemLayout>level 2, item 1</TreeItemLayout>
              <Tree>
                <TreeItem itemType="leaf">
                  <TreeItemLayout>level 3, item 1</TreeItemLayout>
                </TreeItem>
              </Tree>
            </TreeItem>
          </Tree>
        </TreeItem>
        <TreeItem itemType="leaf">
          <TreeItemLayout>level 1, item 3</TreeItemLayout>
        </TreeItem>
      </Tree>
      <hr />
      <h2>Dynamic Tree</h2>
      {renderTree(treeData)}
    </div>
  );
};

export default Default;
